name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v0.0.1
        with:
          host: https://sonar.weilbyte.net/
          login: ${{ secrets.sonarToken }}

